In [33]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [34]:
dict_data = load_boston()
data = pd.DataFrame(dict_data.data,columns=dict_data.feature_names)
data['target_class'] = dict_data.target
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,target_class
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [35]:
train_data, test_data = train_test_split(data, test_size=0.3, random_state=12)
train_data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,target_class
251,0.21409,22.0,5.86,0.0,0.4310,6.438,8.9,7.3967,7.0,330.0,19.1,377.07,3.59,24.8
465,3.16360,0.0,18.10,0.0,0.6550,5.759,48.2,3.0665,24.0,666.0,20.2,334.40,14.13,19.9
137,0.35233,0.0,21.89,0.0,0.6240,6.454,98.4,1.8498,4.0,437.0,21.2,394.08,14.59,17.1
311,0.79041,0.0,9.90,0.0,0.5440,6.122,52.8,2.6403,4.0,304.0,18.4,396.90,5.98,22.1
406,20.71620,0.0,18.10,0.0,0.6590,4.138,100.0,1.1781,24.0,666.0,20.2,370.22,23.34,11.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,0.10612,30.0,4.93,0.0,0.4280,6.095,65.1,6.3361,6.0,300.0,16.6,394.62,12.40,20.1
253,0.36894,22.0,5.86,0.0,0.4310,8.259,8.4,8.9067,7.0,330.0,19.1,396.90,3.54,42.8
390,6.96215,0.0,18.10,0.0,0.7000,5.713,97.0,1.9265,24.0,666.0,20.2,394.43,17.11,15.1
155,3.53501,0.0,19.58,1.0,0.8710,6.152,82.6,1.7455,5.0,403.0,14.7,88.01,15.02,15.6
331,0.05023,35.0,6.06,0.0,0.4379,5.706,28.4,6.6407,1.0,304.0,16.9,394.02,12.43,17.1

In [36]:
x_test, y_test = test_data.drop(columns=['target_class']), test_data['target_class']
x_train, y_train = train_data.drop(columns=['target_class']), train_data['target_class']

In [38]:
regressor = LinearRegression()

regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print(y_pred)

[21.91048095 18.5083658   6.96009344 30.74062562 32.89965357 21.53667661
 20.16310279 38.37899611 32.89973913 25.94315732 22.97775704 22.04274562
 20.79973896 22.62866483 33.68107212 44.55520877 20.77066377 28.84648668
 24.08839896 27.68404006 33.80864308 13.4291918  22.65965537 12.90931693
 25.60897981 21.41173001 20.63591137 14.25186769 26.06158199 37.85590185
 25.98840441 27.75683541 17.38232888 32.4577542  42.47612838 18.01864709
 21.54250069 40.21492853 14.17508389 25.32998864 17.64098089 24.56380331
 21.2451465  34.24995932 19.05134907 18.29700993 20.32002755 15.93718127
 37.48736588 24.03865823 26.04385721 20.78100562 15.85401788 25.16517861
 18.41736558 18.01688465 23.32709701 19.73559064 19.67989059 20.71441626
 20.18357786 29.96129436 22.71025202 18.21459883 18.4924243  25.74709767
 27.38829612 12.77702515 23.97966827 39.56295313 13.59789091 12.4228721
 21.56265266 19.72283168 18.33003836  8.67410148 21.94981112 12.83185024
 22.92786572 30.30575503 25.80840458 21.36416778 30.55641717 16.99537733
 13.52657836 20.70580959 27.95152064 16.33122126 26.36450495 21.50499765
 22.70028165 19.77803073 31.29449479  8.28489093 29.87840428 21.06725255
 23.55643933 17.4254784  33.61105676 17.05972193 33.97084899 21.27943819
 29.97219514 24.0009301  19.1464871   6.11241182 11.52770953 19.8944987
 27.32009251 31.57902467 34.44052278 27.004782   27.54482338 17.42865632
 29.68501154 24.22255007 35.43433684 17.96484707 31.41092983 40.31375137
 35.72969909 22.80825245 28.70464717 34.4133168  32.17108616 21.02224953
 25.00522855 16.55722883 23.80044495 19.32635118 29.29307184 20.52020729
  3.47239082 21.31244363 16.28353707 29.04733337  4.99163644 20.75951496
 36.22219952  0.70039766 20.92860419 26.61827744 20.8583521  20.11818432
 18.36565166 25.16608859 14.63679209 11.27216844 15.4230956  38.67934658
 36.60054289 21.52888443]

In [41]:
mse = mean_squared_error(y_test, y_pred) ** 0.5
print(mse)

5.054621414195831